stages:
  - test
  - build:jar
  - build:docker-image

tests:
  services:
    - docker:dind

  variables:
    DOCKER_HOST: "tcp://docker:2375"

  image: adoptopenjdk/openjdk11:latest
  stage: test
  script:
    - ./gradlew clean test

build:docker-image:
  services:
    - docker:dind

  variables:
    DOCKER_HOST: "tcp://docker:2375"

  image: docker:latest
  stage: build
  script:
    - ./build.sh

build:jar:
  image: adoptopenjdk/openjdk11:latest
  stage: build
  script:
    - ./gradlew clean build -x test