services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"

tests:
  image: adoptopenjdk/openjdk11:latest
  stage: test
  script:
    - ./gradlew clean test

build:
  stage: build
  script:
    - ./gradlew clean build -x test
    - ./build.sh